version: "2.4"
services:
  backend:
    build:
      context: ./backend
      #dockerfile: Dockerfile #If the file is named differently, you need this line also
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/app
    restart: always
  frontend:
    build:
      context: ./frontend
      #dockerfile: Dockerfile #If the file is named differently, you need this line also
    ports:
      - "4050:3000"
    volumes:
      - ./frontend:/opt/app
    restart: always
